dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts

apiVersion: v2
name: icinga-kubernetes
description: Icinga Kubernetes
maintainers:
  - name: Icinga GmbH
    email: info@icinga.com
    url: https://icinga.com

type: application
version: 0.2.0
appVersion: "0.2.0"
